"""initial schema: backtest_runs table

Revision ID: e50f045840d1
Revises: 
Create Date: 2026-06-12 08:47:14.295674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50f045840d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('strategy_params', sa.JSON(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('cagr', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_strategy_name'), ['strategy_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_ticker'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_created_at'))

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
